### ISSUE TITLE
CSS checklist 1

### ISSUE THREAD

**Issue by annahsieh** [annahsieh/fa21-cse110-lab3#5]
- [x] inline CSS
- [x] internal CSS
- [x] comment
- [x] color
    - [x] rgb(r, g, b) or rgba(r, g, b, a)  
    - [x] #FFF or #FFFFFF  
    - [x] hsl(h, s, l) or hsla(h, s, l, a)  
    - [x] name
- [x] background-color
- [x] unit
    - [x] 3 unique relative units
    - [x] 3 unique absolute units
- [x] text
    - [x] color
    - [x] text-decoration
    - [x] text-align
- [x] display
    - [x] at least 2 from: none, block, inline-block, inline
- [x] sizing
    - [x] height / width
    - [x] max-width / min-width
- [x] position 
    - [x] at least 2 from: static, relative, fixed, absolute, sticky applied to the position property
- [x] pseudo-class
    - [x] :hover
    - [x] :active
- [x] layouts
    - [x] apply flex to the display property
        - [x] more than 2 children 
        - [x] at least 3 flexbox related attributes
    - [x] apply grid to the display property
        - [x] more than 2 children
        - [x] at least 3 grid related properties
- [x] responsiveness
    - [x] at least 1 query based on the screen width
- [x] fonts
    - [x] 3rd party font
