### ISSUE TITLE
CSS checklist 2

### ISSUE THREAD

**Issue by annahsieh** [annahsieh/fa21-cse110-lab3#7]
- [ ] display
    - [ ] at least 2 from: none, block, inline-block, inline
- [ ] sizing
    - [ ] height / width
    - [ ] max-width / min-width
- [ ] position 
    - [ ] at least 2 from: static, relative, fixed, absolute, sticky applied to the position property
- [x] pseudo-class
    - [x] :hover
    - [x] :active
- [ ] layouts
    - [ ] apply flex to the display property
        - [ ] at least 2 children 
        - [ ] at least 3 flexbox related attributes
    - [ ] apply grid to the display property
        - [ ] at least 2 children
        - [ ] at least 3 grid related properties
- [ ] responsiveness
        - [ ] at least 1 query based on the screen width
- [ ] fonts
    - [ ] 3rd party font
